### PR TITLE
add a feature = "serde"

### PR DESCRIPTION
**Pull request by Eh2406**
This is a start on the serde feature from #6.

I know there are things that need to be addressed before merging.

- [x] Add to the docs
- [ ] Add test
- [x] Make sure that ci runs these test
- [ ] Find some way for serde to fail to deserialize inputs that brake invariants.

I could use some advice on how best to deal with each of these issues.

### CODE REVIEW

**Comment by Eh2406** [comment]
I was able to get travis to test with and without "serde". I did not find documentation on what the environment variable `ARCH=` did. So I left it in, but we may want to check that it is still doing what you intended.

**Comment by Eh2406** [comment]
The validation can be done with `#[serde(deserialize_with = "path")]` I think.

**Comment by vks** [comment]
Thanks, looks good so far. For the tests you just need to make sure to use `cfg_attr(feature = "serde")`. Checking invariants when deserializing can be done at a later point.

**Comment by Eh2406** [comment]
What tests do you think are needed?

**Comment by vks** [comment]
I was thinking of a test for each supported estimator that adds a few values and then checks invariance under serializing to and deserializing from e.g. JSON.

**Comment by Eh2406** [comment]
How does this look?

**Comment by vks** [comment]
It looks fine, thanks!

**Pull request merged**
